columnSuffix: null
contentColumnType: string
fieldGroup: ab97eced-2c66-43df-8866-f5604d148745 # Config
handle: defaultSocialShareImage
instructions: 'Per Facebook: "Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. " It does not need to be this proportion. Minimum size if you can''t do this size is 200x200.'
name: 'Default Social Share Image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:3494e64c-42b6-49c4-9e9d-8afe189c15c9' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:3494e64c-42b6-49c4-9e9d-8afe189c15c9' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
