defaultPlacement: end
enableVersioning: true
handle: education
name: Education
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  665742c3-51bb-4c48-8153-aef194693ac4: # Stolte Family Foundation (en-US)
    enabledByDefault: true
    hasUrls: true
    template: sections\education.twig
    uriFormat: 'education/{slug}'
type: channel
