defaultPlacement: end
enableVersioning: true
handle: grantees
name: Grantees
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  665742c3-51bb-4c48-8153-aef194693ac4: # Stolte Family Foundation (en-US)
    enabledByDefault: true
    hasUrls: true
    template: sections/section-generic.twig
    uriFormat: 'our-grantees/{slug}'
structure:
  maxLevels: 1
  uid: bf554aeb-f235-4280-b7c8-5faa89f2d3b3
type: structure
